### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by pandalabme** [halo-sigs/plugin-search-widget#15]
问题描述：搜索功能不生效，提示报错，截图如下
![image](https://github.com/halo-sigs/plugin-search-widget/assets/141545683/474c0093-b390-4968-943c-aa399e514b2f)
网站地址：https://pandalab.me/
主题：[默认](https://github.com/halo-dev/theme-earth)

**Comment by JohnNiang** [comment]
尝试重新“启用”一下搜索插件，看是否能解决问题。

**Comment by pandalabme** [comment]
> 尝试重新“启用”一下搜索插件，看是否能解决问题。

感谢回复，重置->关闭->启用后，问题还是存在
![image](https://github.com/halo-sigs/plugin-search-widget/assets/141545683/3f2ec0fe-77c0-41dc-8180-0e433f68c481)

**Comment by ruibaby** [comment]
我这边直接访问这个 JS 资源是这样的资源：

<img width="1452" alt="image" src="https://github.com/halo-sigs/plugin-search-widget/assets/21301288/44ca68e2-f300-4da1-a7fb-cb6e7f505ce6">

似乎都还没有经过 Halo 。

**Comment by pandalabme** [comment]
> 我这边直接访问这个 JS 资源是这样的页面：
> 
> <img alt="image" width="1452" src="https://user-images.githubusercontent.com/21301288/267893355-44ca68e2-f300-4da1-a7fb-cb6e7f505ce6.png">
> 似乎都还没有经过 Halo 。

找到原因了，是被cloudflare拦截了。谢谢两位大佬！
