### ISSUE TITLE
搜索插件不精确，不好用

### ISSUE THREAD

**Issue by Rainsheep** [halo-sigs/plugin-search-widget#3]
搜索是博客的一个重要功能，帮助我们通过关键字快读找到自己想要的内容。
经过尝试，个人感觉，halo2 的搜索插件及其难用。 试了一下 wordpress/hexo 的搜索还不错，经过对比，从以下几个方面陈述下我个人认为不如意的地方。
整体来说，对于英文还行，对于中文太弱了。

1. 搜索不到问题
我有一篇文章，title 为 "java 安全管理器", 直接搜 title 竟然搜索不到！
搜索关键字 "安全"，也搜索不到。 搜索 "java" 能搜到。 halo 中文用户这么多，希望支持一下。

2. 搜索不全问题
英文情况下，因为中文根本搜不到。
比如我搜索 "java", 仅仅给我列出了一下文章，搜索内容不全
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/42384577/216886534-65412ca4-cf03-4d03-b267-edf5c6dc2481.png">

3. 权重问题
还是这个例子 
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/42384577/216886534-65412ca4-cf03-4d03-b267-edf5c6dc2481.png">
title 中含有 java 的是否应该在前面？ 这个搜寻结果的排序不符合预期，简单说，就是"相关性低的" 在 "相关性高的" 前面。

4. 支持 or
希望可以同时多个关键字定位一篇文章，比如 我输入 "java springboot", 希望可以搜索出三类文章
    a. 同时和 "java" "springboot" 相关的，排在最前面
    b. 只和 "java" 相关的排在后面
    c. 只和 "springboot" 相关的排在后面。

最后，halo2 问世时间还短，作者能做成现在规模已经很棒了，尤其还是开源的，各位作者辛苦了。
但从产品角度出发，halo2 甚至不满足我对于博客的基本需求，它不是一个好的选择，任重而道远。

**Comment by ruibaby** [comment]
感谢反馈，但这个问题与这个插件无关，搜索引擎本身还是在 Halo。你可以向 Halo 再提交一个 issue，因为组织不同，我这边没有办法转移 issue。

**Comment by Rainsheep** [comment]
已经提交至 halo, close
