### ISSUE TITLE
可以搜索到已删除的文章

### ISSUE THREAD

**Issue by Steven-WZH** [halo-sigs/plugin-search-widget#4]
站点: https://blog.steven.tk
![image](https://user-images.githubusercontent.com/113268133/218046087-d89fa377-c9d5-4de8-8855-f66ffac07fc6.png)
这个默认文章我已经删除了

**Comment by JohnNiang** [comment]
See https://github.com/halo-dev/halo/issues/3121 for more.

**Comment by Steven-WZH** [comment]
请问具体怎么解决呢

**Comment by Steven-WZH** [comment]
我已经试过重装插件了，还不行

**Comment by JohnNiang** [comment]
> 请问具体怎么解决呢

当前插件要是无法解决。

目前可重启 Halo 临时解决。

**Comment by Steven-WZH** [comment]
重启了也不行还是可以搜索到

**Comment by JohnNiang** [comment]
> 重启了也不行还是可以搜索到

删除 ~/.halo2/indices/post，再重启试试。

**Comment by Steven-WZH** [comment]
这个目录是放文章的目录吗
删掉是不是文章都没了

**Comment by JohnNiang** [comment]
Hi @Steven-WZH ，这个问题的根本原因已经找到，并且在 https://github.com/halo-dev/halo/pull/3877 中已经解决，等待合并。
